Bmi
js-samuraji/staznam.rs pull request #11
Opened 2020-07-10 14:26 UTC by jelenaandj

2020-07-10 14:34 UTC, BiljanaPavlovic approved these changes
Bravoo

2020-07-10 14:42 UTC, KoracIsidora approved these changes

2020-07-10 16:13 UTC, nenad-abramovic commented on src/components/tools/bmi/Bmi.jsx
> +    let tmp = mass / (height * height) * 10000;
Mogla bi da se doda neka provera da se nebi dobijao NaN ili neke nerealne vrednosti. Npr da osoba ima izmedju 18 i 120, 130 godina, Da mu je telesna masa izmedju 15, 20 i 300 kilograma i da nije visi od 3 metra ili da ima negativnu visinu.

2020-07-10 16:16 UTC, nenad-abramovic requested changes
Mogla bi da dodas neke provere prilikom racunanja BMI-a. Procitaj komentar.

2020-07-10 21:06 UTC, wnikola approved these changes

2020-07-11 17:12 UTC, wnikola commented
Mozda mozemo da stavimo da, kad se izracuna bmi, da se pored reda u tabeli highlightuje i polje za taj bmi, pored reda. Takodje mislim da bi trebalo da stoji i neka indikacija koji je pol selektovan.

2020-07-11 21:36 UTC, BiljanaPavlovic approved these changes

2020-07-11 22:12 UTC, jelenaandj commented on src/components/tools/bmi/Bmi.jsx
> +    let tmp = mass / (height * height) * 10000;
Uradila sam provere.

2020-07-11 22:26 UTC, BiljanaPavlovic approved these changes

2020-07-11 23:26 UTC, BiljanaPavlovic approved these changes

2020-07-12 04:09 UTC, nenad-abramovic approved these changes
Moze da prodje.

2020-07-12 04:09 UTC, merged